### ISSUE TITLE
Fix git's `detected dubious ownership in repository` warning

### ISSUE THREAD

**Issue by lsorber** [radix-ai/poetry-cookiecutter#186]
Problem description and solution: https://www.kenmuse.com/blog/avoiding-dubious-ownership-in-dev-containers/

**Comment by lukin0110** [comment]
I'd add this somewhere in the `Dockerfile` instead of in the `devcontainer.json` and use `system` instead of `global`:
```dockerfile
RUN  git config --system --add safe.directory '*'
```

Reasons:
- Adding it to the Dockerfile will solve the issue in a central place. It will also solve the same issue when the image is used on linux outside a devcontainer/VSCode/codespaces context. Eg: `docker compose run dev`
- Using `system` will add the config to `/etc/gitconfig`. In case `global` is used it will be added to `~/.gitconfig`. But this will make VSCode fail to share gitconfig / credentials.
